sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_script:
  - cargo +nightly clippy --version || ( rustup install nightly && rustup component add clippy-preview --toolchain=nightly )
  - cargo tarpaulin --version || RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  - curl -o /tmp/urchin https://raw.githubusercontent.com/tlevine/urchin/v0.0.6/urchin && chmod +x /tmp/urchin
  - git fetch --unshallow
  - git config remote.$(git remote | head -n1).fetch "+refs/heads/*:refs/remotes/$(git remote | head -n1)/*"
  - git fetch $(git remote | head -n1) master
  - git checkout master
  - git checkout -
script:
  - cargo +nightly clippy
  - ./runtests.sh

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libssl-dev

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: PG5fwwHT7O11YIkVeYwDcD6fdsFlsz4niHhEfnslEKTctQ0Z6ORk1bnIJIFObLb9dtwJ6N//9ebT9iYox5Pl6881339hg11chaTU9/jR66d/QNJUaiW7Prb1+XR1Y4fEsW0krgge5ouSHXpqfzqdEUQ7VPUjvt/Hi2LuSB4YqlQ=
