sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_script:
  - curl -o /tmp/urchin https://raw.githubusercontent.com/tlevine/urchin/v0.0.6/urchin && chmod +x /tmp/urchin
  - git fetch --unshallow
  - git config remote.$(git remote | head -n1).fetch "+refs/heads/*:refs/remotes/$(git remote | head -n1)/*"
  - git fetch $(git remote | head -n1) master
  - git checkout master
  - git checkout -
script:
  - ./runtests.sh

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin`
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libssl-dev

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: I9wtktkiS3ZaOqcWV3yTIoAanTY5537Jvhf7hiXrjbNATrhE74zq1TFmrk+UURLH5WAsqKr47bAVQfr/Mt3xoNeQA4mPwg/6C1ltMyzUMuKoJrWIM5LT2i2cLqLcnFgKilx3KgCl4XUK4nisLDXATS1Cj+cvuj4rl74m+wvqgws=
